version: "2"
services:
  replicator:
    build: "../../"
#    image: "replicator-it:testing"
    volumes:
      - "./replicator-conf:/etc/replicator"
    command: --schema test --applier kafka --binlog-filename binlog.000001
    depends_on:
      - mysql
      - kafka
  mysql:
    image: "mysql:${MYSQL_VERSION}"
    volumes:
      - "./mysql-conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro"
      - "./mysql-conf/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:ro"
    environment:
      MYSQL_ROOT_PASSWORD: mysqlPass
  zookeeper:
    image: "zookeeper:3.3.6"
  kafka:
    image: "wurstmeister/kafka"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "replicator_test_kafka:1:1,replicator_validation:1:1"
    depends_on:
      - zookeeper